const listCateSong = [
    'Nhạc trẻ',
    'Nhạc thiếu nhi',
    'Nhạc vàng',
    'Nhạc rock',
    'Nhạc pop',
    'Nhạc rap',
    'Nhạc hiphop',
    'Nhạc jazz',
    'Nhạc blues',
    'Nhạc điện tử',
    'Nhạc cổ điển',
    'Nhạc dân gian',
    'Nhạc EDM',
    'Nhạc R&B',
    'Nhạc Latin',
    'Nhạc country',
    'Nhạc reggae',
    'Nhạc metal',
    'Nhạc indie',
    'Nhạc punk',
    'Nhạc soul',
    'Nhạc funk',
    'Nhạc hip hop cổ điển',
    'Nhạc dance',
    'Nhạc trữ tình',
    'Nhạc hòa tấu',
    'Nhạc chế',
    'Nhạc cách mạng',
    'Nhạc tây bắc',
    'Nhạc tây nguyên',
    'Nhạc miền Trung',
    'Nhạc miền Nam',
    'Nhạc thiếu nhi Việt Nam',
    'Nhạc thiếu nhi quốc tế',
    'Nhạc phim',
    'Nhạc truyền thống',
    'Nhạc tôn giáo',
    'Nhạc nước ngoài',
];

export default listCateSong;
